# Generated by Django 5.2.17 on 2026-10-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PUBLIC', 'Public Citizen / Guest'), ('OFFICIAL', 'Department Field Officer / Analyst'), ('SUPERADMIN', 'Nodal Head / Disaster Manager')], default='OFFICIAL', max_length=20),
        ),
    ]
